### ISSUE TITLE
Invalid Parameter 

### ISSUE THREAD

**Issue by amrbasha900** [efeone/frappe_meta_integration#22]
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1457, in call
    return fn(*args, **newargs)
  File "apps/frappe_meta_integration/frappe_meta_integration/whatsapp/doctype/whatsapp_cloud_api_settings/whatsapp_cloud_api_settings.py", line 43, in send_test_message
    frappe.throw(response.json().get("error").get("message"))
  File "apps/frappe/frappe/__init__.py", line 504, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 479, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 434, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: (#100) Invalid parameter

**Comment by muhammadmp** [comment]
@SherinKR

**Comment by SherinKR** [comment]
Looks like issue with token.
